# Generated by Django 4.1.1 on 2022-11-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_category',
            field=models.CharField(choices=[('Social Event', 'Social Event'), ('Concert', 'Concert'), ('Music Show', 'Music Show'), ('Movie Show', 'Movie Show')], max_length=30),
        ),
    ]
