# Generated by Django 4.1.1 on 2022-11-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0005_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='event_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_management.event'),
        ),
    ]
